###
POST http://localhost:5200/api/orders/
Content-Type: application/json

{
    "userID": "Muhammad",
    "itemID": "Muhammad",
    "cartItemName": "Muhammad",
    "dateOrdered": "Muhammad",
    "receiverName": "Muhammad",
    "receiverAddress": "Muhammad",
    "receiverNo": "Muhammad",
    "completed": "Muhammad"
}

###
GET  http://localhost:5200/api/product/search/Smart Watch

###
POST http://localhost:5200/api/cart/cart/624382bcf888c34a5ce169de
Content-Type: application/json

{
    "userID": "12098324nefjk",
    "itemID": "1343298un94392",
    "cartItemName": "Lip gloss from maria",
    "cartItemPrice": "233",
    "cartItemQuantity": "12",
    "cartItemImage": "imageLing"
}

###

POST http://localhost:5200/api/wishlist/
Content-Type: application/json

{
    "userID": "12098324nefjk",
    "itemID": "1343298un94392",
    "wishItemName": "Lip gloss from maria",
    "wishItemPrice": "233",
    "wishItemImage": "imageLink"
}

###
DELETE   http://localhost:5200/api/cart/clearcart/6246e0d11d6424b51149e95d


###
PATCH  http://localhost:5200/api/cart/quantity/625201c9a7347bdcee691f56
Content-Type: application/json

{
    "quantity": "2"
}

###

POST http://localhost:5200/api/product/filter/
Content-Type: application/json

{
    "name": [""],
    "brand": ["Apple", "LIGE"],
    "category": ["Smart Watch"]
}