###
POST http://localhost:5200/api/orders/
Content-Type: application/json

{
    "firstname": "Muhammad",
    "lastname": "Muhammad",
    "email": "Muhammad",
    "country": "Muhammad",
    "gender": "Muhammad",
    "password": "Muhammad"
}

###
POST http://localhost:5200/api/users/login
Content-Type: application/json

{
    "email": "Muhammad",
    "password": "Muhammad"
}

###
POST http://localhost:5200/api/cart/cart/624382bcf888c34a5ce169de
Content-Type: application/json

{
    "userID": "12098324nefjk",
    "itemID": "1343298un94392",
    "cartItemName": "Lip gloss from maria",
    "cartItemPrice": "233",
    "cartItemQuantity": "12",
    "cartItemImage": "imageLing"
}

###
GET  http://localhost:5200/api/product/category/Body


###
PATCH  http://localhost:5200/api/cart/quantity/625201c9a7347bdcee691f56
Content-Type: application/json

{
    "quantity": "2"
}